### ISSUE TITLE
make sure members complete safety training for myhal room access and record who has done it, also collect student numbers

### ISSUE THREAD

**Issue by lkunelk** [utra-robosoccer/soccerbot#119]

**Comment by Vuwij** [comment]
How are you gonna organize this information. I don't recommend using a Google sheet. Unless it's the original members list sheet found here. Needs to be recreated. Better method is to make sure everyone is in the Facebook group with all members and add them on GitHub tasks. We also need to make sure everyone's on GitHub.

https://docs.google.com/spreadsheets/d/13FgYLvUG2JUt1Uslx0IyqQIjBoeisvwhsGjtTIWwvBU/edit?usp=drivesdk
