### ISSUE TITLE
Add Path planning through the usage of  navigation and moveit stack

### ISSUE THREAD

**Issue by manx52** [utra-robosoccer/soccerbot#150]

**Comment by Flova** [comment]
If you want some examples here is the description of our navigation stack which is built upon the standard ros navigation stack including move base:
https://github.com/bit-bots/bitbots_navigation/tree/master/bitbots_move_base

And here is our simple move base local planner for walking holonomic robots:
https://github.com/bit-bots/bitbots_navigation/tree/master/bitbots_local_planner

Demos:
https://www.instagram.com/p/CPIe9TlIza7/
https://www.instagram.com/p/CO_ABOvBcO-/
https://user-images.githubusercontent.com/15075613/119226332-cc7feb80-bb08-11eb-82ad-10e885e68371.mp4
