### ISSUE TITLE
Webots sensors datasheet

### ISSUE THREAD

**Issue by manx52** [utra-robosoccer/soccerbot#171]
https://cyberbotics.com/doc/reference/distancesensor#lookup-table

 Position sensors
– The resolution of sensors should match the hardware specifications. For example, a 12 bit rotary encoder
(like in the Dynamixel) has a resolution of 2π
2
12 ≈ 0.0015.
• Accelerometer https://cyberbotics.com/doc/reference/accelerometer
– LUT should be specified
• Gyro https://cyberbotics.com/doc/reference/gyro
– LUT should be specified
• Touch Sensor https://cyberbotics.com/doc/reference/touchsensor
– The 3 different options allowed are Bumper, Force, Force-3d.
– Since the calculation of forces in the simulation is inherently noisy, no extra noise needs to be modeled
for these sensors.

**Comment by Shah-Rajab** [comment]
Details [here](https://docs.google.com/document/d/1TjxAdeptClfnnkwrhZO71uu5jUgflyVT7tsYRbEFjWU/edit)
