### ISSUE TITLE
Knee servo shaft dislocates w.r.t. bearing in the leg

### ISSUE THREAD

**Issue by Shah-Rajab** [utra-robosoccer/soccerbot#179]
Demo in pybullet:
https://youtu.be/DiWEXpE6-Ig

**Comment by lkunelk** [comment]
@manx52 fixed it in 3e4427dd4002b8b876ab72a4d96b1dd344879153

**Comment by Shah-Rajab** [comment]
The calve still needs to be shifted down with this fix.

**Comment by lkunelk** [comment]
@Shah-Rajab was this fixed?

**Comment by Shah-Rajab** [comment]
@lkunelk No
