### ISSUE TITLE
Automate Fusion to URDF to Proto conversion

### ISSUE THREAD

**Issue by lkunelk** [utra-robosoccer/soccerbot#218]
Fusion2Urdf: 
https://github.com/syuntoku14/fusion2urdf

sample auto generated urdf model: 
https://drive.google.com/file/d/1xBrZn4eNRbCGcd7-D4V8L0b-R16vNMsM/view?usp=sharing

simplify urdf collision: 
https://github.com/bit-bots/simplify_urdf_collision

urdf2proto: 
https://github.com/cyberbotics/urdf2webots

To Dos:
- [x] Check current urdf model for errors in collision boxes
- [ ] Mech team to look for mass/inertia values discrepancies in current model vs actual model
- [ ] ensure urdf script output works in gazebo/pybullet and look at mass/inertia values
- [ ] test simplify collision script
- [x] test proto script

After running automation script some manual steps still need to be done:
- add pressure sensor
- add imu sensor
- add camera sensor
- add motor parameters
- specify joint limits
- add jerseys
- check vetex count on the model (ensure its small for efficient simulation)

**Comment by sabrinalokman** [comment]
- Fusion2Urdf and urdf2proto script is working
- Collision box added with urdf2proto script 
- Just need to specify joints limit and add sensors on proto file after.
- Useful for next version of robot

**Comment by acrylic-origami** [comment]
### Improved Fusion to URDF repo

For Fusion to URDF conversion use [**this fork**](https://github.com/SpaceMaster85/fusion2urdf) of the linked fusion2urdf repo. Big features:

- **Allows linked components** so you no longer have to break links
- Does not change the file anymore, so you can continue working without reopening
- Claims to allow nested components (I have not tested this thoroughly)

Minor caveats (possibly of the original repo too):
- Joint and link orders are random
- You cannot suppress features in the timeline
