### ISSUE TITLE
Torso Design

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccerbot#452]
- [ ] Adding IMU to the front panel. @kkmd02 
 - [ ] Finding a solution to the tight clearance from the USB-A connector on the carrier board to the back plate. @Shah-Rajab 
 - [ ] Finding a cable for the USB-micro A connector to mini-B connector on the NUCLEO board. @Shah-Rajab 
 - [ ] Providing the CAD models of the NUCLEO PCB stack up. @Shah-Rajab 
 - [ ] Adding a power switching to the top of the torso. @Shah-Rajab & TBD
 - [ ] Battery selection with the tighter final dimensions. @Shah-Rajab & @mx266 
 - [ ] Adding handle mechanism to the body. @kkmd02 
 - [ ] Verifying cable runs in and out of the torso. @Shah-Rajab

**Comment by Shah-Rajab** [comment]
PCB stack progress is tracked here:
https://github.com/utra-robosoccer/soccerbot/issues/478

**Comment by Shah-Rajab** [comment]
Provided by @mx266 :
"For battery on the wall  the max dimension is 121mm x 37mm x 60mm. With battery on the wall expand to the max, the battery in the middle can have a max dimension of 111mm x 67mm x 24.5mm. This did not consider the expansion of the battery and with the max dimension used it will make the components have less than 2mm of space in between."

Tentative battery selection:
 - Wall: https://hobbyking.com/en_us/turnigy-lihv-high-capacity-5200mah-3s2p-12c-multi-rotor-lipo-pack-xt60.html
