### ISSUE TITLE
Leg Servo Selection and CADing

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccerbot#453]
- [x] Select the servos to use in Bez 2.0
 - [x] Modify the joints in CAD to accommodate the selected servos.

**Comment by Shah-Rajab** [comment]
Current planning:
- 2 x xl430 for hip joints that rotate along the z-axis. Buy 1-2 more for spares.
- 4 x xm430 with 1-2 spares
- 6 x MX64 with 2 spares
@manx52 to update the team with our latest inventory of Dynamixel servos.

Location of the MX64s to be decided.

**Comment by manx52** [comment]
So it seems like for legs:
xl430: leg_motor_0
xm430: leg_motor_1, leg_motor_2
mx64: leg_motor_3, leg_motor_4, leg_motor_5

Need to verify with velocity data

**Comment by Shah-Rajab** [comment]
From @Vuwij :
![image](https://user-images.githubusercontent.com/24711934/170811871-bc6ee349-98f9-4c9b-8fdb-66c61852f380.png)

**Comment by Shah-Rajab** [comment]
@acrylic-origami is the order looking good?

**Comment by Shah-Rajab** [comment]
From the pic:
1: MX28
2,3: xm430
4,5,6: MX64

**Comment by Shah-Rajab** [comment]
@mx266
