### ISSUE TITLE
Arm & Neck Servo Selection and CADing

### ISSUE THREAD

**Issue by Shah-Rajab** [utra-robosoccer/soccerbot#476]
- [x] Select the servos to use in Bez 2.0
 - [x] Modify the joints in CAD to accommodate the selected servos.

**Comment by Shah-Rajab** [comment]
@Vuwij @manx52 how necessary are reading back from the neck and arm servos and PID tuning them?
Considering using hobby servos without modifications for those joints in Bez 2.0.

@manx52 to provide torque and speed data from running get up trajectories on similar sized models.

**Comment by Vuwij** [comment]
Neck and arm do not need to be highly accurate
