### ISSUE TITLE
Visualize ball kicking zone in rviz

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccerbot#702]

**Comment by Vuwij** [comment]
https://github.com/utra-robosoccer/soccerbot/blob/435278dbd135f0f8cc2596e92a2eed7dd3992bb4/soccer_strategy/src/soccer_strategy/robot_controlled.py#L72-L112

**Comment by Vuwij** [comment]
Add a cone to show the can kick

**Comment by sumiyuan** [comment]
when called can_kick visualize the cone
